config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get 'home/about'
  resources :users do
    member do
     get :following, :followers
    end
  end

  resources :relationships,only: [:create, :destroy]

  resources :books do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comment, dependent: :destroy
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}

  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, except: [:top, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception

  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  #sign_out後のredirect先変更する。rootパスへ。rootパスはhome topを設定済み。
  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    #sign_upの際にnameのデータ操作を許。追加したカラム。
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create

		book_comment = BookComment.new(post_comment_params)
		book_comment.user_id = current_user.id
		book_comment.book_id = params[:book_id]
		book_comment.save
		redirect_to book_path(params[:book_id])
	end

	def destroy
		book_comment = BookComment.find(params[:id])
		book_comment.destroy
		redirect_back(fallback_location: root_path)

	end

	private
	def post_comment_params
	    params.require(:book_comment).permit(:comment)
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
  	@book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
    @book_comments = @book.book_comments.reverse_order
  end

  def index
  	@book = Book.new
    @books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    if @book.user_id != current_user.id
        redirect_to books_path
    end
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		 book = Book.find(params[:book_id])
         favorite = current_user.favorites.new(book_id: book.id)
         favorite.save
         redirect_back(fallback_location: root_path)
	end

	def destroy
		 book = Book.find(params[:book_id])
         favorite = current_user.favorites.find_by(book_id: book.id)
         favorite.destroy
         redirect_back(fallback_location: root_path)
	end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
    if current_user != @user
        redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>


	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<%= form_for(@book) do |f| %>
		<% if @book.errors.any? %>
			<h3><%= @book.errors.count %>error occurrence</h3><!--エラーメッセ-->
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
	<% end %>
	
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<%= form_for(@book) do |f| %>
		<% if @book.errors.any? %>
			<h3><%= @book.errors.count %>error occurrence</h3><!--エラーメッセ-->
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		<% end %>
	<% end %>
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to (book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>

				<% if @book.favorited_by?(current_user) %>
					<td><%= link_to book_favorites_path(@book), method: :delete do %>
				      <i class="fas fa-heart" aria-hidden="true" style="color: pink;"></i>
				      <%= book.favorites.count %> いいね</td>
			 		<% end %>
				<% else %>
			  		<td><%= link_to book_favorites_path(book), method: :post do %>
				      <i class="fas fa-heart-o" aria-hidden="true"></i>
				      <%= book.favorites.count %> いいね</td>
					<% end %>
			  	<% end %>

			  		<td>コメント数:<%= book.book_comments.count %></td>

				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user%>

		<h2>New book</h2>
		<%= render 'books/newform', book: @new_book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>

				<% if @book.favorited_by?(current_user) %>
					<td><%= link_to book_favorites_path(@book), method: :delete do %>
				      <i class="fas fa-heart" aria-hidden="true" style="color: pink;"></i>
				      <%= @book.favorites.count %> いいね</td>
			 		<% end %>
				<% else %>
			  		<td><%= link_to book_favorites_path(@book), method: :post do %>
				      <i class="fa fa-heart-o" aria-hidden="true" style="color: pink;"></i>
				      <%= @book.favorites.count %> いいね</td>
					<% end %>
			  	<% end %>

			  		<td>コメント数:<%= @book.book_comments.count %></td>

			  		<% if @book.user == current_user  %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
		</table>

				<div style="margin-bottom: 50px">
				<%= form_for [@book, @book_comment] do |f| %>
				        <%= f.text_area :comment, size: "100x6",placeholder: "コメントはこちらにお願いします" %>
				    	<%= f.submit "送信" %>
				<% end %>
				</div>

			<% @book_comments.each do |book_comment| %>
			   <div class="col-xs-12 ", style="margin-top:10px; position: relative;">
					<div class="col-xs-10 well", style="word-wrap: break-word; margin-bottom:0;">
						<%= book_comment.comment %>
					</div>

					<% if @book.user == current_user  %>

						<%= link_to "Destroy",book_book_comment_path(book_comment.book_id,book_comment.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger  pull-right destroy_book_#{book_comment.id}", style:"position: absolute; bottom: 0;" %>

					<% end %>
				</div>
			<% end %>
	</div>
</div>

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "Follow", class: "btn btn-success" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == user %>
  <div id="follow_form">
  <% if current_user.following?(user) %>
    <%= render 'unfollow', user: user %>
  <% else %>
    <%= render 'follow', user: user %>
  <% end %>
  </div>
<% end %>

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

		<% user ||= current_user %>
		<tr>
			<th>follows</th>
			<th><%= link_to user.following.count, following_user_path(user) %></th>
		</tr>

		<tr>
			<th>followes</th>
			<th><%= link_to user.followers.count, followers_user_path(user) %></th>
		</tr>
</table>

      <%= render 'users/follow_form', user: user %>

<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
    <div class="col-xs-3">
    	<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
    </div>

<div class="col-xs-9">
		<h2>Users</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="4"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
					<tr>
						<td>
							<%= link_to (user) do %>
							<%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to user.name, user %></td>
						<td>フォロー数:<%= user.following.count %></td>
						<td>フォロワー数:<%= user.followers.count %></td>
					<% if current_user.id != user.id %> 
					<!-- ログインユーザとターゲットユーザが違う時 -->
						<% if current_user.following?(user) %>
						<!-- ログインユーザーがターゲットユーザーをフォローしているか？ -->
						<!-- following?はモデルに定義されている -->
  							<td>
  							<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }) do |f| %>
  									<%= f.submit "フォロー外す", class: "btn btn-primary" %>
  							<% end %>
  							</td>
						<% else %>
							<td>
								<%= form_for(current_user.active_relationships.build) do |f| %>
  								<%= hidden_field_tag :followed_id, user.id %>

  								<%= f.submit "フォローする", class: "btn btn-primary" %>
  								<% end %>
  							</td>
						<% end %>
					<% else %>
						<td></td>
					<% end %>
				  		<td><%= link_to "show", user_path(user.id) %></td>
				   </tr>
			  <% end %>

			 </tbody>
		 </table>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to (book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{@user.id}" %></td>
					<td><%= book.body %></td>
					<td>コメント数:<%= book.book_comments.count %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>

app/views/users/show_follow.html.erb
<h2>Follower Users</h2>
		
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="4"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
					<tr>
						<td>
							<%= link_to (user) do %>
							<%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to user.name, user %></td>
						<td>フォロー数:<%= user.following.count %></td>
						<td>フォロワー数:<%= user.followers.count %></td>
					<% if current_user.id != user.id %>
					<!-- ログインユーザとターゲットユーザが違う時 -->
						<% if current_user.following?(user) %>
						<!-- ログインユーザーがターゲットユーザーをフォローしているか？ -->
						<!-- following?はモデルに定義されている -->
							<td>
	  							<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete }) do |f| %>
	  									<%= f.submit "フォロー外す", class: "btn btn-primary" %>
	  							<% end %>
	  						</td>
	  					<% else %>
	  						<td>
								<%= form_for(current_user.active_relationships.build) do |f| %>
									<%= hidden_field_tag :followed_id, user.id %>

	  								<%= f.submit "フォローする", class: "btn btn-primary" %>
	  								<% end %>
	  						</td>
	  					<% end %>
					 <% else %>
					  		<td></td>
					<% end %>
					  		<td><%= link_to "show", user_path(user.id) %></td>
					 </tr>
			  	<% end %>

			 </tbody>
		 </table>